# Generated by Django 6.0.5 on 2026-05-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('priming_prompt', models.TextField(blank=True)),
                ('language_hint', models.CharField(blank=True, max_length=10)),
                ('model_override', models.CharField(blank=True, max_length=120)),
                ('schema_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanners', to='accounts.account')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'slug'), name='uniq_scanner_account_slug')],
            },
        ),
    ]
