# Generated by Django 6.0.5 on 2026-05-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('files', '0001_initial'),
        ('scanners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('extracting', 'Extracting'), ('locating', 'Locating'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='queued', max_length=16)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=200)),
                ('extracted_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pages_processed', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='accounts.account')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='files.storedfile')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanners.scanner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanFieldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=400)),
                ('data_type', models.CharField(max_length=40)),
                ('original_value', models.TextField(blank=True)),
                ('canonical_value', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('page_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('attempts', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_results', to='scans.scan')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
